I18n.bn =
  menu:
    schema: "স্কিমা"
    new: "নতুন ..."
    load: "লোড ..."
    save: "রক্ষা"
    save_as: "নতুন করে রক্ষা ..."
    templates: "টেম্পলেট ..."
    properties: "বৈশিষ্ট্য ..."
    share: "বিতরণ ..."
    import: "ইম্পোর্ট ..."
    edit: "সম্পাদন করো"
    undo: "পূর্বাবস্থায় আসো"
    redo: "পুনরায় করো"
    insert: "ইনসার্ট"
    table: "টেবিল"
    note: "নোট"
    view: "পরিদর্শন"
    show_minimap: "মিনিম্যাপ দেখাও"
    hide_minimap: "মিনিম্যাপ লুকাও"
    show_sidebar: "সাইডবার দেখাও"
    hide_sidebar: "সাইডবার লুকাও"
    sort_items: "আইটেমগুলো গুছাও"
    linetype: "লাইনের ধরন"
    bezier: "বেজিয়ের"
    cornered: "করনার্ড"
    options: "বৈশিষ্ট্য ..."
    export: "এক্সপোর্ট"
    sql: "এস কিউ এল ..."
    image: "ছবি ..."
    help: "সহায়তা"
    index: "সূচক"
    changes: "পরিবর্তনগুলো"
    shortcuts: "কীবোর্ড শর্টকাট"
    feedback: "প্রতিক্রিয়া"
    about: "ইহা সম্পর্কে"
    guest: "গেস্ট"
    login: "লগ ইন"
    logout: "লগ আউট"
    settings: "সেটিংস"
  panel:
    history: "ইতিহাস"
    last_versions_label: "এই স্কিমার গত ১০ ভার্সন:"
    properties: "বৈশিষ্ট্য"
    properties_schema_name: "স্কিমার নাম:"
    properties_database: "ডাটাবেস:"
    comments: "মন্তব্যগুলো"
    comment_placeholder: "তোমার মন্তব্য এখানে লিপিবদ্ধ করো"
    send: "পাঠাও"
  dialog:
    new_schema: "নতুন স্কিমা"
    new_schema_title: "খেতাব"
    new_schema_database: "ডাটাবেইস"
    new_schema_type_info: """ "জেনেরিক" ধরনের ডাটাবেস নির্বাচন করলে সবধরনের ডাটাবেসের জন্য এস কিউ এল উৎপন্ন করতে পারবে; কিন্তু তোমার কাছে শুধুমাত্র জেনেরিক ডাটা টাইপ ব্যাবহারের অনুমতি থাকবে। """
    new_schema_create_new: "নতুন স্কিমা তৈরি কর"
    load_schema: "স্কিমা লোড কর"
    load_schema_your_schemas: "তোমার স্কিমাগুলো:"
    load_schema_schema_name: "স্কিমার নাম"
    load_schema_database: "ডাটাবেস"
    load_schema_last_save: "শেষ রক্ষাটি"
    load_schema_shared_with_you: "তোমার সাথে বিতরণ করা স্কিমাগুলো:"
    load_schema_owner: "মালিক"
    saveas: "... হিসেবে সংরক্ষণ"
    saveas_title: "খেতাব"
    saveas_button: "... হিসেবে সংরক্ষণ"
    templates: "টেম্পলেটগুলো"
    templates_schema_name: "স্কিমার নাম"
    templates_database: "ডাটাবেস"
    templates_description: "বিবরণ"
    properties: "স্কিমার বৈশিষ্ট্য"
    properties_title: "খেতাব"
    properties_publish: "টেম্পলেট আকারে প্রকাশ করো"
    properties_template_info: "(টেম্পলেটগুলো সব ব্যাবহারকারীর কাছে দৃশ্যমান)"
    properties_delete_schema: "স্কিমা মুছো"
    properties_delete_alert: "(এই স্কিমা এবং এর সাথে যুক্ত সব মন্তব্যগুলো তুমি স্থায়ীভাবে মুছে ফেলবে)"
    properties_save: "পরিবর্তন রক্ষা কর"
    share: "বিতরণ"
    share_info: "তুমি তোমার স্কিমা ৫ জন ব্যবহারকারীর কাছে বিতরণ করতে পারো"
    share_email: "ইমেইল"
    share_access: "প্রবেশাধিকার"
    share_read_only: "শুধুমাত্র পাঠযোগ্য"
    share_read_write: "পাঠযোগ্য এবং লিখনযোগ্য"
    share_send_email: "ইমেইল দ্বারা আমন্ত্রণ পাঠাও"
    share_invite_button: "আমন্ত্রণ"
    share_collaborators: "সহযোগীগণ:"
    import: "এস কিউ এল ইম্পোর্ট"
    login_email: "ইমেইল"
    login_password: "পাসওয়ার্ড"
    login_button: "লগ ইন"
    login_forgot_password: "আমি আমার পাসওয়ার্ড ভুলে গিয়েছি"
    options: "বিকল্প"
    options_line_colors: "লাইনের রং"
    options_language: "ভাষা"
    options_save_changes: "পরিবর্তনগুলো রক্ষা করো"
    export_sql: "এস কিউ এল এক্সপোর্ট"
    export_sql_generate: "এস কিউ এল তৈরি"
    export_sql_download: "এস কিউ এল ফাইল ডাউনলোড"
    export_image: "ছবি এক্সপোর্ট"
    export_image_zoomin: "বড় কর"
    export_image_zoomout: "ছোট কর"
    export_image_reset: "রিসেট"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "সহায়তা"
    shortcuts: "কীবোর্ড শর্টকাট"
    help_changelog: "পরিবর্তনগুলো"
    feedback: "প্রতিক্রিয়া"
    feedback_type: "প্রতিক্রিয়ার ধরন"
    feedback_bug: "প্রোগ্রাম ত্রুটি প্রতিবেদন"
    feedback_feature: "বৈশিষ্ট্য অনুরোধ"
    feedback_help: "সহায়তা"
    feedback_other: "অন্যকিছু"
    feedback_message: "মেসেজ"
    feedback_button: "প্রতিক্রিয়া পাঠাও"
    about: "dbdesigner.net সম্পর্কে"
    user_settings: "ব্যাবহারকারীর সেটিংস"
    user_settings_username: "ইউজারনেম"
    user_settings_email: "ইমেইল"
    user_settings_save: "পরিবর্তন রক্ষা কর"
    login: "লগ ইন"
    close: "বন্ধ"
  designer:
    save_note_edit: "রক্ষা"
    cancel_note_edit: "বাতিল"
    delete_note: "মোছো"
    table_save: "রক্ষা"
    table_cancel: "বাতিল"
    table_delete: "টেবিল মোছো"
    table_add_field: "ফিল্ড সংযোজন"
    field_name: "নাম"
    field_type: "ধাঁচ"
    field_size: "আকার"
    field_default: "ডিফল্ট"
    field_allow_nulls: "নাল অনুমোদন"
    field_primary_key: "প্রাইমারি কী"
    field_foreign_key: "ফরেন কী"
    field_save: "রক্ষা"
    field_update: "হালনাগাদ"
    field_cancel: "বাতিল"
    field_delete: "ফিল্ড মোছো"
    field_delete_alert: "তুমি কি নিশ্চিতভাবে ফিল্ডটি মুছতে চাও?\n(অনুমোদন ছাড়া মোছার জন্য শিফট ধরে রাখো)"
    field_ref_table: "রেফ. টেবিল"
    field_ref_field: "রেফ. ফিল্ড"
  alerts:
    delete_schema: "তুমি কি নিশ্চিত ভাবে স্কিমাটি মুছতে চাও?"
    server_error: "সার্ভারে সমস্যা দেখা দিয়েছে"
    schema_owner_error: "শুধুমাত্র স্কিমার মালিক বিতরণ সেটিংস বদলাতে পারে"
    login_to_use_this_function: "এই ফাংশনটি ব্যাবহার করতে তোমার লগ ইন করতে হবে"