I18n.en =
  menu:
    schema: "Schema"
    new: "New ..."
    load: "Load ..."
    save: "Save"
    save_as: "Save As ..."
    templates: "Templates ..."
    properties: "Properties ..."
    share: "Share ..."
    import: "Import ..."
    edit: "Edit"
    undo: "Undo"
    redo: "Redo"
    insert: "Insert"
    table: "Table"
    note: "Note"
    view: "View"
    show_minimap: "Show Minimap"
    hide_minimap: "Hide Minimap"
    show_sidebar: "Show Sidebar"
    hide_sidebar: "Hide Sidebar"
    sort_items: "Sort Items"
    linetype: "Line Type"
    bezier: "Bezier"
    cornered: "Cornered"
    options: "Options ..."
    export: "Export"
    sql: "Sql ..."
    image: "Image ..."
    help: "Help"
    index: "Index"
    changes: "Changes"
    shortcuts: "Keyboard Shortcuts"
    feedback: "Feedback"
    about: "About"
    guest: "Guest"
    login: "Login"
    logout: "Logout"
    settings: "Settings"
  panel:
    history: "History"
    last_versions_label: "Last 10 versions of this schema:"
    properties: "Properties"
    properties_schema_name: "Schema Name:"
    properties_database: "Database:"
    comments: "Comments"
    comment_placeholder: "Enter your comment here"
    send: "Send"
  dialog:
    new_schema: "New Schema"
    new_schema_title: "Title"
    new_schema_database: "Database"
    new_schema_type_info: """Selecting the "generic" database type will allow you to generate SQL for all the databases; but you will only have access to the generic datatypes."""
    new_schema_create_new: "Create New Schema"
    load_schema: "Load Schema"
    load_schema_your_schemas: "Your Schemas:"
    load_schema_schema_name: "Schema Name"
    load_schema_database: "Database"
    load_schema_last_save: "Last Save"
    load_schema_shared_with_you: "Schemas shared with you:"
    load_schema_owner: "Owner"
    saveas: "Save As"
    saveas_title: "Title"
    saveas_button: "Save As"
    templates: "Templates"
    templates_schema_name: "Schema Name"
    templates_database: "Database"
    templates_description: "Description"
    properties: "Schema Properties"
    properties_title: "Title"
    properties_publish: "Publish as template"
    properties_template_info: "(Templates are visible to every user)"
    properties_delete_schema: "Delete Schema"
    properties_delete_alert: "(You will permanently delete this schema and all associated comments)"
    properties_save: "Save Changes"
    share: "Share"
    share_info: "You can share your schema with up to 5 users"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "Invite"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "I forgot my password"
    options: "Options"
    options_line_colors: "Line Colors"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    help: "Help"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "Changes"
    feedback: "Feedback"
    feedback_type: "Feedback Type"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "Help"
    feedback_other: "Other"
    feedback_message: "Message"
    feedback_button: "Send Feedback"
    about: "About dbdesigner.net"
    user_settings: "User Settings"
    user_settings_username: "Username"
    user_settings_email: "E-mail"
    user_settings_save: "Save Changes"
    login: "Login"
    close: "Close"
  designer:
    save_note_edit: "Save"
    cancel_note_edit: "Cancel"
    delete_note: "Delete"
    table_save: "Save"
    table_cancel: "Cancel"
    table_delete: "Delete Table"
    table_add_field: "Add field"
    field_name: "Name"
    field_type: "Type"
    field_size: "Size"
    field_default: "Default"
    field_allow_nulls: "Allow nulls"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Save"
    field_update: "Update"
    field_cancel: "Cancel"
    field_delete: "Delete Field"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
  alerts:
    delete_schema: "Are you sure you want to delete this schema?"
    server_error: "A server error occurred"
    schema_owner_error: "Only the schema owner can change share settings"
    login_to_use_this_function: "You should login to use this function"