I18n.id =
  menu:
    schema: "Skema"
    new: "Baru ..."
    load: "Muat ..."
    save: "Simpan"
    save_as: "Simpan sebagai ..."
    templates: "Template ..."
    properties: "Properti ..."
    share: "Bagikan ..."
    import: "Impor ..."
    edit: "Edit"
    undo: "Batal"
    redo: "Ulangi"
    insert: "Sisipkan"
    table: "Tabel"
    note: "Catatan"
    view: "Tampilan"
    show_minimap: "Perlihatkan minimap"
    hide_minimap: "Sembunyikan minimap"
    show_sidebar: "Perlihatkan sidebar"
    hide_sidebar: "Sembunyikan sidebar"
    sort_items: "Urutkan item"
    linetype: "Jenis garis"
    bezier: "Melengkung"
    cornered: "Bersudut"
    options: "Opsi ..."
    export: "Ekspor"
    sql: "SQL ..."
    image: "Gambar ..."
    help: "Bantuan"
    index: "Indeks"
    changes: "Perubahan"
    shortcuts: "Shortcut keyboard"
    feedback: "Umpan Balik"
    about: "Tentang"
    guest: "Tamu"
    login: "Masuk"
    logout: "Keluar"
    settings: "Pengaturan"
  panel:
    history: "Histori"
    last_versions_label: "10 versi terakhir skema ini:"
    properties: "Properti"
    properties_schema_name: "Nama skema:"
    properties_database: "Basis data:"
    comments: "Komentar"
    comment_placeholder: "Sampaikan komentar Anda di sini"
    send: "Kirim"
  dialog:
    new_schema: "Skema baru"
    new_schema_title: "Judul"
    new_schema_database: "Basis data"
    ew_schema_type_info: """Memilih jenis basis data "generic" memungkinkan Anda menggenerate perintah SQL untuk semua jenis basis data; tetapi Anda hanya dapat mengakses jenis-jenis data generic."""
    new_schema_create_new: "Buat Skema Baru"
    load_schema: "Muat skema"
    load_schema_your_schemas: "Skema Anda:"
    load_schema_schema_name: "Nama Skema"
    load_schema_database: "Basis data"
    load_schema_last_save: "Terakhir disimpan"
    load_schema_shared_with_you: "Skema yang dibagi bersama Anda:"
    load_schema_owner: "Pemilik"
    saveas: "Simpan sebagai"
    saveas_title: "Judul"
    saveas_button: "Simpan sebagai"
    templates: "Template"
    templates_schema_name: "Nama Skema"
    templates_database: "Basis data"
    templates_description: "Deskkripsi"
    properties: "Properti Skema"
    properties_title: "Judul"
    properties_publish: "Publikasikan sebagai template"
    properties_template_info: "(Template dapat dilihat oleh semua pengguna)"
    properties_delete_schema: "Hapus skema"
    properties_delete_alert: "(Anda akan menghapus skema ini dan seluruh komentarnya)"
    properties_save: "Simpan perubahan"
    share: "Bagikan"
    share_info: "Anda hanya dapat membagikan skema ke 5 pengguna"
    share_email: "E-mail"
    share_access: "Akses"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Kirim e-mail ajakan"
    share_invite_button: "Ajak"
    share_collaborators: "Kolaborator:"
    import: "Impor SQL"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Masuk"
    login_forgot_password: "Saya lupa apa passwordnya"
    options: "Pilihan"
    options_line_colors: "Warna garis"
    options_language: "Bahasa"
    options_save_changes: "Simpan perubahan"
    export_sql: "Ekspor SQL"
    export_sql_generate: "Buatkan SQL"
    export_sql_download: "Unduh file SQL"
    export_image: "Ekspor gambar"
    export_image_zoomin: "Perbesar"
    export_image_zoomout: "Perkecil"
    export_image_reset: "Kembali ke pengaturan awal"
    export_image_open_in_new_tab: "Buka gambar di tab baru"
    help: "Bantuan"
    shortcuts: "Shortcut keyboard"
    help_changelog: "Perubahan"
    feedback: "Masukan"
    feedback_type: "Jenis masukan"
    feedback_bug: "Laporan bug"
    feedback_feature: "Permintaan fitur"
    feedback_help: "Bantuan"
    feedback_other: "Lainnya"
    feedback_message: "Pesan"
    feedback_button: "Kirim masukan"
    about: "Tentang dbdesigner.net"
    user_settings: "Pengaturan pengguna"
    user_settings_username: "Nama pengguna"
    user_settings_email: "Alamat e-mail"
    user_settings_save: "Simpan perubahan"
    login: "Masuk"
    close: "Tutup"
  designer:
    save_note_edit: "Simpan"
    cancel_note_edit: "Batalkan"
    delete_note: "Hapus"
    table_save: "Simpan"
    table_cancel: "Batalkan"
    table_delete: "Hapus tabel"
    table_add_field: "Tambahkan bidang"
    field_name: "Nama"
    field_type: "Jenis"
    field_size: "Ukuran"
    field_default: "Default"
    field_allow_nulls: "Perbolehkan kosong"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Simpan"
    field_update: "Perbarui"
    field_cancel: "Batalkan"
    field_delete: "Hapus bidang"
    field_delete_alert: "Apakah Anda yakin akan menghapus bidang ini?\n(Tekan shift pada keyboard untuk menghapus tanpa konfirmasi)"
    field_ref_table: "Referensi tabel"
    field_ref_field: "Referensi bidang"
  alerts:
    delete_schema: "Apakah Anda yakin akan menghapus skema ini?"
    server_error: "Terjadi kesalahan pada server"
    schema_owner_error: "Hanya pemilik skema yang dapat mengganti pengaturan pembagian"
    login_to_use_this_function: "Anda harus masuk untuk menggunakan fungsi ini"
