I18n.ru =
  menu:
    schema: "Схема"
    new: "Новая ..."
    load: "Загрузить ..."
    save: "Сохранить"
    save_as: "Сохранить как ..."
    templates: "Шаблоны ..."
    properties: "Свойства ..."
    share: "Совместный доступ ..."
    import: "Импортировать ..."
    edit: "Редактирование"
    undo: "Отмена"
    redo: "Повтор"
    insert: "Вставка"
    table: "Таблица"
    note: "Заметка"
    view: "Вид"
    show_minimap: "Показать миникарту"
    hide_minimap: "Скрыть миникарту"
    sort_items: "Сортировать элементы"
    linetype: "Тип линий"
    bezier: "Безье"
    cornered: "С прямым углом"
    options: "Опции ..."
    export: "Экспорт"
    sql: "Sql ..."
    image: "Изображение ..."
    help: "Справка"
    index: "Информация"
    changes: "Изменения"
    shortcuts: "Горячие клавиши"
    feedback: "Обратная связь"
    about: "О сайте"
    guest: "Гость"
    login: "Авторизоваться"
    logout: "Выйти"
  panel:
    history: "История"
    last_versions_label: "Последние 10 версий схемы:"
    properties: "Свойства"
    properties_schema_name: "Название схемы:"
    properties_database: "База данных:"
    comments: "Комментарии"
    comment_placeholder: "Оставьте свой комментарий здесь"
    send: "Отправить"
  dialog:
    new_schema: "Новая схемах"
    new_schema_title: "Заголовок"
    new_schema_database: "База данных"
    new_schema_type_info: """Выбор "универсального" типа базы данных позволит вам генерировать SQL код для всех баз данных, но будут доступны только родительские типы данных."""
    new_schema_create_new: "Создать новую схему данных"
    load_schema: "Загрузить схему"
    load_schema_your_schemas: "Ваши схемы:"
    load_schema_schema_name: "Имя схемы"
    load_schema_database: "База данных"
    load_schema_last_save: "Последнее сохранённое"
    load_schema_shared_with_you: "Схемы в совместном с Вами доступом:"
    load_schema_owner: "Создатель"
    saveas: "Сохранить как"
    saveas_title: "Заголовок"
    saveas_button: "Сохранить как"
    templates: "Шаблоны"
    templates_schema_name: "Имя схемы"
    templates_database: "База данных"
    templates_description: "Описание"
    properties: "Свойства схемы"
    properties_title: "Заголовок"
    properties_publish: "Опубликовать, как шаблон"
    properties_template_info: "(Шаблон будет видет всем)"
    properties_delete_schema: "Удалить схему"
    properties_delete_alert: "(Вы удалите схему со всеми связанными с ней комментариями)"
    properties_save: "Сохранить изменения"
    share: "Совместный доступ"
    share_info: "Вы можете ввести работу одновременно с пятью пользователями"
    share_email: "E-mail"
    share_access: "Доступ"
    share_read_only: "Только просмотр"
    share_read_write: "Просмотр и редактирование"
    share_send_email: "Отправить приглашение на e-mail"
    share_invite_button: "Добавить пользователя"
    share_collaborators: "Collaborators:"
    login_email: "E-mail"
    login_password: "Password"
    login_button: "Login"
    login_forgot_password: "I forgot my password"
    options: "Options"
    options_line_colors: "Line Colors"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "Download SQL file"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    help: "Help"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "Changes"
    feedback: "Feedback"
    feedback_type: "Feedback Type"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "Help"
    feedback_other: "Other"
    feedback_message: "Message"
    feedback_button: "Send Feedback"
    about: "About dbdesigner.net"
    user_settings: "User Settings"
    login: "Login"
    close: "Close"
  designer:
    save_note_edit: "Save"
    cancel_note_edit: "Cancel"
    delete_note: "Delete"
    table_save: "Save"
    table_cancel: "Cancel"
    table_delete: "Delete Table"
    table_add_field: "Add field"
    field_name: "Name"
    field_type: "Type"
    field_size: "Size"
    field_default: "Default"
    field_allow_nulls: "Allow nulls"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Save"
    field_update: "Update"
    field_cancel: "Cancel"
    field_delete: "Delete Field"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
