I18n.ru =
  menu:
    schema: "Схема"
    new: "Новая ..."
    load: "Загрузить ..."
    save: "Сохранить"
    save_as: "Сохранить как ..."
    templates: "Шаблоны ..."
    properties: "Свойства ..."
    share: "Совместное редактирование ..."
    import: "Импортировать ..."
    edit: "Правка"
    undo: "Отмена"
    redo: "Повтор"
    insert: "Вставка"
    table: "Таблица"
    note: "Заметка"
    view: "Вид"
    show_minimap: "Показать миникарту"
    hide_minimap: "Скрыть миникарту"
    show_sidebar: "Show Sidebar"
    hide_sidebar: "Hide Sidebar"
    sort_items: "Сортировать элементы"
    linetype: "Тип линий"
    bezier: "Безье"
    cornered: "С прямым углом"
    options: "Опции ..."
    export: "Экспорт"
    sql: "Sql ..."
    image: "Изображение ..."
    help: "Справка"
    index: "Информация"
    changes: "Изменения"
    shortcuts: "Горячие клавиши"
    feedback: "Обратная связь"
    about: "О сайте"
    guest: "Гость"
    login: "Авторизоваться"
    logout: "Выйти"
  panel:
    history: "История"
    last_versions_label: "Последние 10 версий схемы:"
    properties: "Свойства"
    properties_schema_name: "Название схемы:"
    properties_database: "База данных:"
    comments: "Комментарии"
    comment_placeholder: "Оставьте свой комментарий здесь"
    send: "Отправить"
  dialog:
    new_schema: "Новая схема"
    new_schema_title: "Заголовок"
    new_schema_database: "База данных"
    new_schema_type_info: """Выбор "универсального" типа базы данных позволит вам генерировать SQL код для всех баз данных, но будут доступны только родительские типы данных."""
    new_schema_create_new: "Создать новую схему данных"
    load_schema: "Загрузить схему"
    load_schema_your_schemas: "Ваши схемы:"
    load_schema_schema_name: "Имя схемы"
    load_schema_database: "База данных"
    load_schema_last_save: "Последнее сохранение"
    load_schema_shared_with_you: "Схемы с совместным редактирования.:"
    load_schema_owner: "Создатель"
    saveas: "Сохранить как"
    saveas_title: "Заголовок"
    saveas_button: "Сохранить"
    templates: "Шаблоны"
    templates_schema_name: "Имя схемы"
    templates_database: "База данных"
    templates_description: "Описание"
    properties: "Свойства схемы"
    properties_title: "Заголовок"
    properties_publish: "Опубликовать, как шаблон"
    properties_template_info: "(Шаблон будут видеть все пользователи)"
    properties_delete_schema: "Удалить схему"
    properties_delete_alert: "(Вы удалите схему со всеми связанными с ней комментариями)"
    properties_save: "Сохранить изменения"
    share: "Совместное редактирование"
    share_info: "Вы можете ввести работу одновременно с пятью пользователями"
    share_email: "E-mail"
    share_access: "Доступ"
    share_read_only: "Только просмотр"
    share_read_write: "Просмотр и редактирование"
    share_send_email: "Отправить приглашение на e-mail"
    share_invite_button: "Добавить пользователя"
    share_collaborators: "Пользователи, имеющие доступ к схеме:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Пароль"
    login_button: "Логин"
    login_forgot_password: "Восстановление пароля"
    options: "Опции"
    options_line_colors: "Цвет линии"
    options_language: "Язык"
    options_save_changes: "Сохранить изменения"
    export_sql: "Экспортировать SQL"
    export_sql_generate: "Генерировать SQL"
    export_sql_download: "Загрузить SQL файл"
    export_image: "Экспортировать изображение"
    export_image_zoomin: "Увеличение"
    export_image_zoomout: "Уменьшение"
    export_image_reset: "Сброс"
    help: "Справка"
    shortcuts: "Горячие клавиши"
    help_changelog: "Изменения"
    feedback: "Обратная связь"
    feedback_type: "Тип обратной связь"
    feedback_bug: "Сообщить об ошибке"
    feedback_feature: "Фичреквест"
    feedback_help: "Помощь"
    feedback_other: "Другое"
    feedback_message: "Сообщение"
    feedback_button: "Отправить сообщение"
    about: "Про dbdesigner.net"
    user_settings: "Настройки пользователя"
    user_settings_username: "Username"
    user_settings_email: "E-mail"
    user_settings_save: "Save Changes"
    login: "Логин"
    close: "Закрыть"
    settings: "Settings"
  designer:
    save_note_edit: "Сохранить"
    cancel_note_edit: "Отменить"
    delete_note: "Удалить"
    table_save: "Сохранить"
    table_cancel: "Отменить"
    table_delete: "Удалить таблицу"
    table_add_field: "Добавить новое поле"
    field_name: "Имя"
    field_type: "Тип"
    field_size: "Размер"
    field_default: "Значение по умолчанию"
    field_allow_nulls: "Разрешить nulls"
    field_primary_key: "Первичный ключ"
    field_foreign_key: "Внешний ключ"
    field_save: "Сохранить"
    field_update: "Обновить"
    field_cancel: "Отменить"
    field_delete: "Удалить поле"
    field_delete_alert: "Вы уверены, что хотите удалить это поле?\n(удерживайте Shift, чтобы удалить без подтверждения)"
    field_ref_table: "Ref. Таблица"
    field_ref_field: "Ref. Поле"
  alerts:
    delete_schema: "Are you sure you want to delete this schema?"
    server_error: "A server error occurred"
    schema_owner_error: "Only the schema owner can change share settings"
    login_to_use_this_function: "You should login to use this function"