I18n.tr =
  menu:
    schema: "Şema"
    new: "Yeni ..."
    load: "Yükle ..."
    save: "Kaydet"
    save_as: "Farklı Kaydet ..."
    templates: "Şablonlar ..."
    properties: "Özellikler ..."
    share: "Paylaş ..."
    import: "İçeri aktar ..."
    edit: "Düzenle"
    undo: "Geri Al"
    redo: "Yinele"
    insert: "Ekle"
    table: "Tablo"
    note: "Not"
    view: "Görünüm"
    show_minimap: "Haritayı Göster"
    hide_minimap: "Haritayı Gizle"
    sort_items: "Sırala"
    linetype: "Çizgi Şekli"
    bezier: "Bezier"
    cornered: "Köşeli"
    options: "Ayarlar ..."
    export: "Oluştur"
    sql: "Sql ..."
    image: "Resim ..."
    help: "Yardım"
    index: "Indeks"
    changes: "Değişiklikler"
    shortcuts: "Klavye Kısayolları"
    feedback: "Geribildirim"
    about: "Hakkında"
    guest: "Misafir"
    login: "Giriş"
    logout: "Çıkış"
  panel:
    history: "Geçmiş"
    last_versions_label: "Bu şemanın son 10 hali:"
    properties: "Özellikler"
    properties_schema_name: "Şema Adı:"
    properties_database: "Veritabanı:"
    comments: "Yorumlar"
    comment_placeholder: "Yorumunuzu buraya yazın"
    send: "Gönder"
  dialog:
    new_schema: "Yeni Şema"
    new_schema_title: "Başlık"
    new_schema_database: "Veritabanı"
    new_schema_type_info: "Generic veritabanını seçtiğinizde tüm veritabanları için SQL çıktısı alabilirsiniz; fakat sadece genel veritiplerini seçebilirsiniz"
    new_schema_create_new: "Yeni Şema Oluştur"
    load_schema: "Yükle"
    load_schema_your_schemas: "Senin Şemaların:"
    load_schema_schema_name: "Şema adı"
    load_schema_database: "Veritabanı"
    load_schema_last_save: "Son Kaydedilme"
    load_schema_shared_with_you: "Seninle paylaşılan şemalar:"
    load_schema_owner: "Kullanıcı"
    saveas: "Farklı Kaydet"
    saveas_title: "Başlık"
    saveas_button: "Farklı Kaydet"
    templates: "Şablonlar"
    templates_schema_name: "Şema Adı"
    templates_database: "Veritabanı"
    templates_description: "Açıklama"
    properties: "Şema Ayarları"
    properties_title: "Başlık"
    properties_publish: "Şablon olarak yayınla"
    properties_template_info: "(Şablonları tüm kullanıcılar görebilir)"
    properties_delete_schema: "Şemayı Sil"
    properties_delete_alert: "(Bu şema ve bağlı tüm yorumlar silinecek)"
    properties_save: "Değişiklikleri Kaydet"
    share: "Paylaş"
    share_info: "Şemanızı en fazla 5 kullanıcıyla paylaşabilirsiniz"
    share_email: "E-posta"
    share_access: "Erişim"
    share_read_only: "Sadece okuma"
    share_read_write: "Okuma ve yazma"
    share_send_email: "Davet için e-posta gönder"
    share_invite_button: "Davet Et"
    share_collaborators: "Erişimi olan kullanıcılar:"
    login_email: "E-posta"
    login_password: "Şifre"
    login_button: "Giriş"
    login_forgot_password: "Şifremi unuttum"
    options: "Ayarlar"
    options_line_colors: "Çizgi Renkleri"
    options_language: "Dil"
    options_save_changes: "Değişiklikleri Kaydet"
    export_sql: "SQL Oluştur"
    export_sql_generate: "SQL Oluştur"
    export_sql_download: "SQL dosyasını indir"
    export_image: "Resim"
    export_image_zoomin: "Yakınlaştır"
    export_image_zoomout: "Uzaklaştır"
    export_image_reset: "Sıfırla"
    help: "Yardım"
    shortcuts: "Klavye Kısayolları"
    help_changelog: "Değişiklikler"
    feedback: "Geribildirim"
    feedback_type: "Geribildirim şekli"
    feedback_bug: "Hata Bildirimi"
    feedback_feature: "Yeni Özellik İsteği"
    feedback_help: "Yardım"
    feedback_other: "Diğer"
    feedback_message: "Mesajınız"
    feedback_button: "Gönder"
    about: "DbDesigner.net Hakkında"
    user_settings: "Kullanıcı Ayarları"
    login: "Giriş"
    close: "Kapat"
  designer:
    save_note_edit: "Kaydet"
    cancel_note_edit: "İptal"
    delete_note: "Sil"
    table_save: "Kaydet"
    table_cancel: "İptal"
    table_delete: "Tabloyu Sil"
    table_add_field: "Alan Ekle"
    field_name: "İsim"
    field_type: "Tip"
    field_size: "Boyut"
    field_default: "Varsayılan"
    field_allow_nulls: "Boş Değer"
    field_primary_key: "Birincil Anahtar"
    field_foreign_key: "Yabancı Anahtar"
    field_save: "Kaydet"
    field_update: "Kaydet"
    field_cancel: "İptal"
    field_delete: "Alanı Sil"
    field_delete_alert: "Bu alanı silmek istediğinizden emin misiniz?\n(onay olmadan silmek için silerken SHIFT tuşunu basılı tutun)"
    field_ref_table: "Ref. Tablo"
    field_ref_field: "Ref. Alan"