I18n.vi =
  menu:
    schema: "Lược đồ"
    new: "Tạo mới ..."
    load: "Mở ..."
    save: "Lưu"
    save_as: "Lưu như ..."
    templates: "Mẫu sẵn ..."
    properties: "Thuộc tính ..."
    share: "Chia sẻ ..."
    import: "Nhập ..."
    edit: "Chỉnh sửa"
    undo: "Hủy bỏ"
    redo: "Làm lại"
    insert: "Chèn"
    table: "Bảng"
    note: "Ghi chú"
    view: "Hiển thị"
    show_minimap: "Hiển thị Minimap"
    hide_minimap: "Ẩn Minimap"
    show_sidebar: "Hiển thị Sidebar"
    hide_sidebar: "Ẩn Sidebar"
    sort_items: "Sắp xếp Items"
    linetype: "Kiểu đường"
    bezier: "Cong"
    cornered: "Thẳng"
    options: "Tùy chỉnh ..."
    export: "Xuất"
    sql: "Sql ..."
    image: "Hình ảnh ..."
    help: "Trợ giúp"
    index: "Chỉ mục"
    changes: "Thay đổi"
    shortcuts: "Phím tắt"
    feedback: "Feedback"
    about: "Về"
    guest: "Khách"
    login: "Đăng nhập"
    logout: "Đăng ký"
    settings: "Cài đặt"
  panel:
    history: "Lịch sử"
    last_versions_label: "10 phiên bản cuổi cùng của lược đồ này:"
    properties: "Thuộc tính"
    properties_schema_name: "Tên lược dồ:"
    properties_database: "Cơ sở dữ liệu:"
    comments: "Bình luận"
    comment_placeholder: "Thêm bình luận của bạn ở đây"
    send: "Gửi"
  dialog:
    new_schema: "Tạo lược đồ mới"
    new_schema_title: "Tiêu đề"
    new_schema_database: "Cơ sở dữ liệu"
    new_schema_type_info: """Lựa chọn loại cơ sở dữ liệu "generic" sẽ cho phép bạn sinh SQL cho tất cả dữ liệu; nhưng bạn chỉ có thể truy cập đến kiểu dữ liệu generic mà thôi."""
    new_schema_create_new: "Tạo lược đồ mới"
    load_schema: "Mở lược đồ"
    load_schema_your_schemas: "Lước đồ của bạn:"
    load_schema_schema_name: "Tên lược đồ"
    load_schema_database: "Cơ sở dữ liệu"
    load_schema_last_save: "Lưu lần cuối cùng"
    load_schema_shared_with_you: "Chia sẻ lược đồ với:"
    load_schema_owner: "Chủ sở hữu"
    saveas: "Lưu như"
    saveas_title: "Tiêu đề"
    saveas_button: "Lưu như"
    templates: "Mẫu sẵn"
    templates_schema_name: "Tên lược đồ"
    templates_database: "Cơ sở dữ liệu"
    templates_description: "Mô tả"
    properties: "Thuộc tính lược đồ"
    properties_title: "Tiêu đề"
    properties_publish: "Xuất như mẫu sẵn"
    properties_template_info: "(Mẫu sẵn sẽ được thấy bởi tất cả mọi người)"
    properties_delete_schema: "Xóa lược đồ"
    properties_delete_alert: "(Bạn có chắc muốn xóa lược đồ này và các bình luận liên quan không?)"
    properties_save: "Lưu thay đổi"
    share: "Chia sẻ"
    share_info: "Bạn có thể chia sẻ lược đồ này tới 5 người dùng"
    share_email: "E-mail"
    share_access: "Truy cập"
    share_read_only: "Chỉ đọc"
    share_read_write: "Đọc và ghi"
    share_send_email: "Gửi lời mời qua email"
    share_invite_button: "Mời"
    share_collaborators: "Cộng sự:"
    import: "Nhập Sql"
    login_email: "E-mail"
    login_password: "Mật khẩu"
    login_button: "Đăng nhập"
    login_forgot_password: "Quên mật khẩu"
    options: "Tùy chỉnh"
    options_line_colors: "Màu đường"
    options_language: "Ngôn ngữ"
    options_save_changes: "Lưu thay đổi"
    export_sql: "Xuất như tập tin SQL"
    export_sql_generate: "Sinh SQL"
    export_sql_download: "Tải tập tin SQL xuống"
    export_image: "Xuât như hình ảnh"
    export_image_zoomin: "Phóng to"
    export_image_zoomout: "Thu nhỏ"
    export_image_reset: "Khôi phục"
    help: "Trợ giúp"
    shortcuts: "Phím tắt"
    help_changelog: "Thay đổi"
    feedback: "Feedback"
    feedback_type: "Kiểu Feedback"
    feedback_bug: "Báo lỗi"
    feedback_feature: "Yêu cầu đặc trưng"
    feedback_help: "Trợ giúp"
    feedback_other: "Khác"
    feedback_message: "Tin nhắn"
    feedback_button: "Gửi Feedback"
    about: "Về dbdesigner.net"
    user_settings: "Cài đặt người dùng"
    user_settings_username: "Tên người dùng"
    user_settings_email: "E-mail"
    user_settings_save: "Lưu thay đổi"
    login: "Đăng nhập"
    close: "Đóng"
  designer:
    save_note_edit: "Lưu"
    cancel_note_edit: "Hủy bỏ"
    delete_note: "Xóa"
    table_save: "Lưu"
    table_cancel: "Hủy bỏ"
    table_delete: "Xóa bảng"
    table_add_field: "Thêm trường"
    field_name: "Tên"
    field_type: "Kiểu"
    field_size: "Kích thước"
    field_default: "Mặc định"
    field_allow_nulls: "Cho phép rỗng"
    field_primary_key: "Khóa chính"
    field_foreign_key: "Khóa ngoại"
    field_save: "Lưu"
    field_update: "Cập nhật"
    field_cancel: "Hủy"
    field_delete: "Xóa trường"
    field_delete_alert: "Bạn có chắc muốn xóa trường này?\n(Giữ SHIFT+DELETE để khỏi xác nhận)"
    field_ref_table: "Bảng than chiếu"
    field_ref_field: "Trường tham chiếu"
  alerts:
    delete_schema: "Bạn có chắc muốn xóa lược đồ này?"
    server_error: "Lỗi hệ thống"
    schema_owner_error: "Chỉ có chủ lược đồ mới có thể thay đổi cài đặt"
    login_to_use_this_function: "Bạn nên đăng nhập để sử dụng chức năng này"
